/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ERUiModule extends AbstractERUiModule {

	public ERUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
