/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.n7.gls.er.xtext.ide.contentassist.antlr.internal.InternalERParser;
import fr.n7.gls.er.xtext.services.ERGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ERParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ERGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ERGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives_3(), "rule__Model__Alternatives_3");
			builder.put(grammarAccess.getCardinalAccess().getAlternatives(), "rule__Cardinal__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
			builder.put(grammarAccess.getRelationAccess().getGroup_4(), "rule__Relation__Group_4__0");
			builder.put(grammarAccess.getPartAccess().getGroup(), "rule__Part__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getEntitiesAssignment_3_0(), "rule__Model__EntitiesAssignment_3_0");
			builder.put(grammarAccess.getModelAccess().getRelationsAssignment_3_1(), "rule__Model__RelationsAssignment_3_1");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getRelationAccess().getNameAssignment_1(), "rule__Relation__NameAssignment_1");
			builder.put(grammarAccess.getRelationAccess().getPartsAssignment_3(), "rule__Relation__PartsAssignment_3");
			builder.put(grammarAccess.getRelationAccess().getPartsAssignment_4_1(), "rule__Relation__PartsAssignment_4_1");
			builder.put(grammarAccess.getPartAccess().getNameAssignment_0(), "rule__Part__NameAssignment_0");
			builder.put(grammarAccess.getPartAccess().getCardinalAssignment_2(), "rule__Part__CardinalAssignment_2");
			builder.put(grammarAccess.getPartAccess().getEntityAssignment_3(), "rule__Part__EntityAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ERGrammarAccess grammarAccess;

	@Override
	protected InternalERParser createParser() {
		InternalERParser result = new InternalERParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ERGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ERGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
