/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl.ui.internal.MydslActivator;

public class ERUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("fr.n7.gls.er.xtext.ER");
	}

}
