/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.gls.er.xtext.ERRuntimeModule;
import fr.n7.gls.er.xtext.ERStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ERIdeSetup extends ERStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ERRuntimeModule(), new ERIdeModule()));
	}
	
}
