/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractERScopeProvider extends DelegatingScopeProvider {
}
