/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractERValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.n7.gls.er.xtext.er.ErPackage.eINSTANCE);
		return result;
	}
}
