/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.n7.gls.er.xtext.parser.antlr.internal.InternalERParser;
import fr.n7.gls.er.xtext.services.ERGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ERParser extends AbstractAntlrParser {

	@Inject
	private ERGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalERParser createParser(XtextTokenStream stream) {
		return new InternalERParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ERGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ERGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
