/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.er;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gls.er.xtext.er.Model#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.gls.er.xtext.er.Model#getEntities <em>Entities</em>}</li>
 *   <li>{@link fr.n7.gls.er.xtext.er.Model#getRelations <em>Relations</em>}</li>
 * </ul>
 *
 * @see fr.n7.gls.er.xtext.er.ErPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.gls.er.xtext.er.ErPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.gls.er.xtext.er.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gls.er.xtext.er.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see fr.n7.gls.er.xtext.er.ErPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gls.er.xtext.er.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see fr.n7.gls.er.xtext.er.ErPackage#getModel_Relations()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getRelations();

} // Model
