/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.er;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gls.er.xtext.er.Part#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.gls.er.xtext.er.Part#getCardinal <em>Cardinal</em>}</li>
 *   <li>{@link fr.n7.gls.er.xtext.er.Part#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see fr.n7.gls.er.xtext.er.ErPackage#getPart()
 * @model
 * @generated
 */
public interface Part extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.gls.er.xtext.er.ErPackage#getPart_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.gls.er.xtext.er.Part#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Cardinal</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.gls.er.xtext.er.Cardinal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinal</em>' attribute.
   * @see fr.n7.gls.er.xtext.er.Cardinal
   * @see #setCardinal(Cardinal)
   * @see fr.n7.gls.er.xtext.er.ErPackage#getPart_Cardinal()
   * @model
   * @generated
   */
  Cardinal getCardinal();

  /**
   * Sets the value of the '{@link fr.n7.gls.er.xtext.er.Part#getCardinal <em>Cardinal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinal</em>' attribute.
   * @see fr.n7.gls.er.xtext.er.Cardinal
   * @see #getCardinal()
   * @generated
   */
  void setCardinal(Cardinal value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see fr.n7.gls.er.xtext.er.ErPackage#getPart_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link fr.n7.gls.er.xtext.er.Part#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

} // Part
