/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ERRuntimeModule extends AbstractERRuntimeModule {
}
