/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ERStandaloneSetup extends ERStandaloneSetupGenerated {

	public static void doSetup() {
		new ERStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
