/*
 * generated by Xtext 2.32.0
 */
package fr.n7.gls.er.xtext.serializer;

import com.google.inject.Inject;
import fr.n7.gls.er.xtext.er.Entity;
import fr.n7.gls.er.xtext.er.ErPackage;
import fr.n7.gls.er.xtext.er.Model;
import fr.n7.gls.er.xtext.er.Part;
import fr.n7.gls.er.xtext.er.Relation;
import fr.n7.gls.er.xtext.services.ERGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ERSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ERGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ErPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ErPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case ErPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case ErPackage.PART:
				sequence_Part(context, (Part) semanticObject); 
				return; 
			case ErPackage.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ErPackage.Literals.ENTITY__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ErPackage.Literals.ENTITY__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEntityAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=ID (entities+=Entity | relations+=Relation)*)
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Part returns Part
	 *
	 * Constraint:
	 *     (name=ID cardinal=Cardinal entity=[Entity|ID])
	 * </pre>
	 */
	protected void sequence_Part(ISerializationContext context, Part semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ErPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ErPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ErPackage.Literals.PART__CARDINAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ErPackage.Literals.PART__CARDINAL));
			if (transientValues.isValueTransient(semanticObject, ErPackage.Literals.PART__ENTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ErPackage.Literals.PART__ENTITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPartAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPartAccess().getCardinalCardinalEnumRuleCall_2_0(), semanticObject.getCardinal());
		feeder.accept(grammarAccess.getPartAccess().getEntityEntityIDTerminalRuleCall_3_0_1(), semanticObject.eGet(ErPackage.Literals.PART__ENTITY, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Relation returns Relation
	 *
	 * Constraint:
	 *     (name=ID parts+=Part parts+=Part*)
	 * </pre>
	 */
	protected void sequence_Relation(ISerializationContext context, Relation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
